"""add process table

Revision ID: 5ad5ffcdd378
Revises: a1a7f06fd541
Create Date: 2023-06-05 11:32:38.146617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad5ffcdd378'
down_revision = 'a1a7f06fd541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_created_at'), 'processes', ['created_at'], unique=False)
    op.create_index(op.f('ix_processes_deleted_at'), 'processes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_processes_updated_at'), 'processes', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processes_updated_at'), table_name='processes')
    op.drop_index(op.f('ix_processes_deleted_at'), table_name='processes')
    op.drop_index(op.f('ix_processes_created_at'), table_name='processes')
    op.drop_table('processes')
    # ### end Alembic commands ###
