"""add process maker tables

Revision ID: d64d9fa3a2ef
Revises: a1a7f06fd541
Create Date: 2023-06-22 07:48:37.600122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64d9fa3a2ef'
down_revision = 'a1a7f06fd541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('action_type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_created_at'), 'action', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_deleted_at'), 'action', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_action_updated_at'), 'action', ['updated_at'], unique=False)
    op.create_table('activity',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('activity_type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_created_at'), 'activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_deleted_at'), 'activity', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activity_updated_at'), 'activity', ['updated_at'], unique=False)
    op.create_table('group',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_created_at'), 'group', ['created_at'], unique=False)
    op.create_index(op.f('ix_group_deleted_at'), 'group', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_group_updated_at'), 'group', ['updated_at'], unique=False)
    op.create_table('process',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_created_at'), 'process', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_deleted_at'), 'process', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_process_updated_at'), 'process', ['updated_at'], unique=False)
    op.create_table('target',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('target_type', sa.String(length=128), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_created_at'), 'target', ['created_at'], unique=False)
    op.create_index(op.f('ix_target_deleted_at'), 'target', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_target_updated_at'), 'target', ['updated_at'], unique=False)
    op.create_table('action_target',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('action_id', 'target_id')
    )
    op.create_index(op.f('ix_action_target_created_at'), 'action_target', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_target_deleted_at'), 'action_target', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_action_target_updated_at'), 'action_target', ['updated_at'], unique=False)
    op.create_table('activity_target',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'target_id')
    )
    op.create_index(op.f('ix_activity_target_created_at'), 'activity_target', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_target_deleted_at'), 'activity_target', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activity_target_updated_at'), 'activity_target', ['updated_at'], unique=False)
    op.create_table('group_member',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('process_admin',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('process_id', 'user_id')
    )
    op.create_table('state',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('state_type', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_created_at'), 'state', ['created_at'], unique=False)
    op.create_index(op.f('ix_state_deleted_at'), 'state', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_state_updated_at'), 'state', ['updated_at'], unique=False)
    op.create_table('request',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('current_state_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('entity_model', sa.String(length=128), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_state_id'], ['state.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_created_at'), 'request', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_deleted_at'), 'request', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_request_updated_at'), 'request', ['updated_at'], unique=False)
    op.create_table('route',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('current_state_id', sa.Integer(), nullable=True),
    sa.Column('next_state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_state_id'], ['state.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_created_at'), 'route', ['created_at'], unique=False)
    op.create_index(op.f('ix_route_deleted_at'), 'route', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_route_updated_at'), 'route', ['updated_at'], unique=False)
    op.create_table('state_activity',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('state_id', 'activity_id')
    )
    op.create_index(op.f('ix_state_activity_created_at'), 'state_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_state_activity_deleted_at'), 'state_activity', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_state_activity_updated_at'), 'state_activity', ['updated_at'], unique=False)
    op.create_table('request_action',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_action_created_at'), 'request_action', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_action_deleted_at'), 'request_action', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_request_action_updated_at'), 'request_action', ['updated_at'], unique=False)
    op.create_table('request_data',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('value', sa.String(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_data_created_at'), 'request_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_data_deleted_at'), 'request_data', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_request_data_updated_at'), 'request_data', ['updated_at'], unique=False)
    op.create_table('request_note',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_note_created_at'), 'request_note', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_note_deleted_at'), 'request_note', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_request_note_updated_at'), 'request_note', ['updated_at'], unique=False)
    op.create_table('request_stakeholder',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('stakeholder_id', sa.Integer(), nullable=True),
    sa.Column('stakeholder_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_stakeholder_created_at'), 'request_stakeholder', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_stakeholder_deleted_at'), 'request_stakeholder', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_request_stakeholder_updated_at'), 'request_stakeholder', ['updated_at'], unique=False)
    op.create_table('route_action',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'action_id')
    )
    op.create_index(op.f('ix_route_action_created_at'), 'route_action', ['created_at'], unique=False)
    op.create_index(op.f('ix_route_action_deleted_at'), 'route_action', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_route_action_updated_at'), 'route_action', ['updated_at'], unique=False)
    op.create_table('route_activity',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'activity_id')
    )
    op.create_index(op.f('ix_route_activity_created_at'), 'route_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_route_activity_deleted_at'), 'route_activity', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_route_activity_updated_at'), 'route_activity', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_activity_updated_at'), table_name='route_activity')
    op.drop_index(op.f('ix_route_activity_deleted_at'), table_name='route_activity')
    op.drop_index(op.f('ix_route_activity_created_at'), table_name='route_activity')
    op.drop_table('route_activity')
    op.drop_index(op.f('ix_route_action_updated_at'), table_name='route_action')
    op.drop_index(op.f('ix_route_action_deleted_at'), table_name='route_action')
    op.drop_index(op.f('ix_route_action_created_at'), table_name='route_action')
    op.drop_table('route_action')
    op.drop_index(op.f('ix_request_stakeholder_updated_at'), table_name='request_stakeholder')
    op.drop_index(op.f('ix_request_stakeholder_deleted_at'), table_name='request_stakeholder')
    op.drop_index(op.f('ix_request_stakeholder_created_at'), table_name='request_stakeholder')
    op.drop_table('request_stakeholder')
    op.drop_index(op.f('ix_request_note_updated_at'), table_name='request_note')
    op.drop_index(op.f('ix_request_note_deleted_at'), table_name='request_note')
    op.drop_index(op.f('ix_request_note_created_at'), table_name='request_note')
    op.drop_table('request_note')
    op.drop_index(op.f('ix_request_data_updated_at'), table_name='request_data')
    op.drop_index(op.f('ix_request_data_deleted_at'), table_name='request_data')
    op.drop_index(op.f('ix_request_data_created_at'), table_name='request_data')
    op.drop_table('request_data')
    op.drop_index(op.f('ix_request_action_updated_at'), table_name='request_action')
    op.drop_index(op.f('ix_request_action_deleted_at'), table_name='request_action')
    op.drop_index(op.f('ix_request_action_created_at'), table_name='request_action')
    op.drop_table('request_action')
    op.drop_index(op.f('ix_state_activity_updated_at'), table_name='state_activity')
    op.drop_index(op.f('ix_state_activity_deleted_at'), table_name='state_activity')
    op.drop_index(op.f('ix_state_activity_created_at'), table_name='state_activity')
    op.drop_table('state_activity')
    op.drop_index(op.f('ix_route_updated_at'), table_name='route')
    op.drop_index(op.f('ix_route_deleted_at'), table_name='route')
    op.drop_index(op.f('ix_route_created_at'), table_name='route')
    op.drop_table('route')
    op.drop_index(op.f('ix_request_updated_at'), table_name='request')
    op.drop_index(op.f('ix_request_deleted_at'), table_name='request')
    op.drop_index(op.f('ix_request_created_at'), table_name='request')
    op.drop_table('request')
    op.drop_index(op.f('ix_state_updated_at'), table_name='state')
    op.drop_index(op.f('ix_state_deleted_at'), table_name='state')
    op.drop_index(op.f('ix_state_created_at'), table_name='state')
    op.drop_table('state')
    op.drop_table('process_admin')
    op.drop_table('group_member')
    op.drop_index(op.f('ix_activity_target_updated_at'), table_name='activity_target')
    op.drop_index(op.f('ix_activity_target_deleted_at'), table_name='activity_target')
    op.drop_index(op.f('ix_activity_target_created_at'), table_name='activity_target')
    op.drop_table('activity_target')
    op.drop_index(op.f('ix_action_target_updated_at'), table_name='action_target')
    op.drop_index(op.f('ix_action_target_deleted_at'), table_name='action_target')
    op.drop_index(op.f('ix_action_target_created_at'), table_name='action_target')
    op.drop_table('action_target')
    op.drop_index(op.f('ix_target_updated_at'), table_name='target')
    op.drop_index(op.f('ix_target_deleted_at'), table_name='target')
    op.drop_index(op.f('ix_target_created_at'), table_name='target')
    op.drop_table('target')
    op.drop_index(op.f('ix_process_updated_at'), table_name='process')
    op.drop_index(op.f('ix_process_deleted_at'), table_name='process')
    op.drop_index(op.f('ix_process_created_at'), table_name='process')
    op.drop_table('process')
    op.drop_index(op.f('ix_group_updated_at'), table_name='group')
    op.drop_index(op.f('ix_group_deleted_at'), table_name='group')
    op.drop_index(op.f('ix_group_created_at'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_activity_updated_at'), table_name='activity')
    op.drop_index(op.f('ix_activity_deleted_at'), table_name='activity')
    op.drop_index(op.f('ix_activity_created_at'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_action_updated_at'), table_name='action')
    op.drop_index(op.f('ix_action_deleted_at'), table_name='action')
    op.drop_index(op.f('ix_action_created_at'), table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###
