"""change role model

Revision ID: edc43a5c39c4
Revises: ce97e10901c0
Create Date: 2019-08-30 16:30:02.513448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc43a5c39c4'
down_revision = 'ce97e10901c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('description', table_name='roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('description', 'roles', ['description'], unique=True)
    # ### end Alembic commands ###
